## Uncomment a line if you want to skip a given category of checks

skip_repository_checks_reason: "not needed for this test"
skip_license_checks_reason: "not needed for this test"
skip_registry_checks_reason: "not needed for this test"
#skip_citation_checks_reason: <reason for skipping goes here>
skip_checklist_checks_reason: "not needed for this test"

ignore_commented_badges: false
