on: [push]

jobs:
  somef_job:
    runs-on: ubuntu-latest
    name: Test somef
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Chechout repo
      uses: actions/checkout@v2  
      
    - name: Set up Python        
      uses: actions/setup-python@v2.2.1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install howfairis
        
    - name: Use howfairis to check citation
      id: vars
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      shell: bash
      run: |
        echo "::set-env name=HAVE_FILE::false"     
        python citation_check.py --url https://github.com/${{ github.repository }}
        if [ "$?" == "0" ]; then
           echo "::set-env name=HAVE_FILE::true"
        fi
    - name: Check outputs
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      shell: pwsh
      run: echo ${{ steps.vars.outputs.HAVE_FILE }}

    # Use SOMEF generate codemeta.json
    - name: Somef with repo-url input
      if:  ${{ steps.vars.outputs.HAVE_FILE }} == 'false'
      uses: KnowledgeCaptureAndDiscovery/somef-github-action@main
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true      
      with:
        repo-url: "https://github.com/${{ github.repository }}"
   
    # Create a PR 
    - name: Create Pull Request
      if:  ${{ steps.vars.outputs.HAVE_FILE }} == 'false'    
      uses: peter-evans/create-pull-request@v3.8.2
      with:
        title: Generating codemeta template
        commit-message: Add codemeta.json template
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        labels: automated pr
        branch: add-codemeta
        # reviewers: ${{ github.repository_owner }} ## Ideally we would add a reviewer.
