on: [push]

jobs:
  somef_job:
    runs-on: ubuntu-latest
    name: Test somef
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Chechout repo
      uses: actions/checkout@v2  
      
    - name: Set up Python        
      uses: actions/setup-python@v2.2.1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install howfairis
        
    - name: Use howfairis to check citation
      id: vars
      run: |   
        python citation_check.py --url https://github.com/${{ github.repository }}
      continue-on-error: true        

    # Use SOMEF generate codemeta.json
    - name: Somef with repo-url input
      uses: KnowledgeCaptureAndDiscovery/somef-github-action@main
      with:
        repo-url: "https://github.com/${{ github.repository }}"
   
    # Create a PR 
    - name: Create Pull Request
      if: failure()    
      uses: peter-evans/create-pull-request@v3.8.2
      with:
        title: Generating codemeta template
        commit-message: Add codemeta.json template
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        labels: automated pr
        branch: add-codemeta
        # reviewers: ${{ github.repository_owner }} ## Ideally we would add a reviewer.
